0101.co.jp,"HTTPSConnectionPool(host='0101.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f4e7cfd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='0101.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f589bc40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
022.co.il,"HTTPConnectionPool(host='0.0.0.0', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f4c4c310>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='0.0.0.0', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f4b97550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
109.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
126,"HTTPSConnectionPool(host='126', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f19b7940>, 'Connection to 126 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='126', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f2f56f40>, 'Connection to 126 timed out. (connect timeout=2)'))"
129,"HTTPSConnectionPool(host='129', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f2f6e4c0>, 'Connection to 129 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='129', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f1b92580>, 'Connection to 129 timed out. (connect timeout=2)'))"
160,"HTTPSConnectionPool(host='160', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f3297580>, 'Connection to 160 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='160', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f1ed2fd0>, 'Connection to 160 timed out. (connect timeout=2)'))"
163.com,"HTTPSConnectionPool(host='163.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f34a48e0>, 'Connection to 163.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='163.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f2147040>, 'Connection to 163.com timed out. (connect timeout=2)'))"
167,"HTTPSConnectionPool(host='167', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f1b924f0>, 'Connection to 167 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='167', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f2147430>, 'Connection to 167 timed out. (connect timeout=2)'))"
179,"HTTPSConnectionPool(host='179', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f2dd09d0>, 'Connection to 179 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='179', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f1ec2430>, 'Connection to 179 timed out. (connect timeout=2)'))"
20.ua,"HTTPSConnectionPool(host='20.ua', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='20.ua', port=443): Read timed out. (read timeout=2)"
20il.co.il,"HTTPSConnectionPool(host='20il.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='20il.co.il', port=443): Read timed out. (read timeout=2)"
210,"HTTPSConnectionPool(host='210', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f3521610>, 'Connection to 210 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='210', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f14c2fa0>, 'Connection to 210 timed out. (connect timeout=2)'))"
24.lv,"HTTPSConnectionPool(host='24.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='24.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
24kitchen.pt,"HTTPSConnectionPool(host='24kitchen.pt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f0249160>, 'Connection to 24kitchen.pt timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.24kitchen.pt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f569eeb0>, 'Connection to www.24kitchen.pt timed out. (connect timeout=2)'))"
24u.jp,"HTTPSConnectionPool(host='24u.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.24u.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
2chblog.jp,"HTTPSConnectionPool(host='2chblog.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f2bac640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='2chblog.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78eff69a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
3,"HTTPSConnectionPool(host='3', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f4d07f40>, 'Connection to 3 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='3', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f3dc2a90>, 'Connection to 3 timed out. (connect timeout=2)'))"
34,"HTTPSConnectionPool(host='34', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f5af7430>, 'Connection to 34 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='34', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f31aa3d0>, 'Connection to 34 timed out. (connect timeout=2)'))"
36,"HTTPSConnectionPool(host='36', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f0521d30>, 'Connection to 36 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='36', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f38023a0>, 'Connection to 36 timed out. (connect timeout=2)'))"
411.ca,"HTTPSConnectionPool(host='411.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))","HTTPSConnectionPool(host='411.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))"
42,"HTTPSConnectionPool(host='42', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f8912fd0>, 'Connection to 42 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='42', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f2c4dd90>, 'Connection to 42 timed out. (connect timeout=2)'))"
43,"HTTPSConnectionPool(host='43', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78ef667f10>, 'Connection to 43 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='43', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f05148e0>, 'Connection to 43 timed out. (connect timeout=2)'))"
4sales.bg,"HTTPSConnectionPool(host='4sales.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='4sales.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
4x4.ee,"HTTPSConnectionPool(host='4x4.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='4x4.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))"
51,"HTTPSConnectionPool(host='51', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f31de550>, 'Connection to 51 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='51', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f2a8c100>, 'Connection to 51 timed out. (connect timeout=2)'))"
76,"HTTPSConnectionPool(host='76', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78eff605b0>, 'Connection to 76 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='76', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78ee6ca7f0>, 'Connection to 76 timed out. (connect timeout=2)'))"
77kaoded.com,"HTTPSConnectionPool(host='www.77kaoded.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.77kaoded.com', port=443): Read timed out. (read timeout=2)"
7lafa.com,"HTTPSConnectionPool(host='7lafa.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='7lafa.com', port=443): Read timed out. (read timeout=2)"
90minut.pl,"HTTPSConnectionPool(host='90minut.pl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f3ad4940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='90minut.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78ee2ef580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
99,"HTTPSConnectionPool(host='99', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f3f341c0>, 'Connection to 99 timed out. (connect timeout=2)'))","HTTPConnectionPool(host='99', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78ee0e3220>, 'Connection to 99 timed out. (connect timeout=2)'))"
9asset.com,"HTTPSConnectionPool(host='9asset.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='9asset.com', port=443): Read timed out. (read timeout=2)"
aa.com.tr,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='aa.com.tr', port=80): Read timed out. (read timeout=2)"
aarda.info,"HTTPConnectionPool(host='aarda.info', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='aarda.info', port=80): Read timed out. (read timeout=2)"
ab.gr,"HTTPSConnectionPool(host='ab.gr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f2afadc0>, 'Connection to ab.gr timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.ab.gr', port=443): Read timed out. (read timeout=2)"
abc-israel.it,"HTTPSConnectionPool(host='www.abc-israel.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.abc-israel.it', port=443): Read timed out. (read timeout=2)"
abc.med.br,"HTTPSConnectionPool(host='www.abc.med.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.abc.med.br', port=443): Read timed out. (read timeout=2)"
abdwap.cyou,"HTTPSConnectionPool(host='abdwap.cyou', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f47f1be0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='abdwap.cyou', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78eede8c40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
abitab.com.uy,"HTTPSConnectionPool(host='abitab.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='abitab.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
able.co.jp,"HTTPSConnectionPool(host='able.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78edd640a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='able.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f3632580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
abnamro.nl,"HTTPSConnectionPool(host='abnamro.nl', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='abnamro.nl', port=80): Read timed out. (read timeout=2)"
abyhom.com,"HTTPSConnectionPool(host='abyhom.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='abyhom.com', port=443): Read timed out. (read timeout=2)"
abz.cz,"HTTPSConnectionPool(host='knihy.abz.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='knihy.abz.cz', port=443): Read timed out. (read timeout=2)"
ac-aix-marseille.fr,"HTTPSConnectionPool(host='ac-aix-marseille.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f3493130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ac-aix-marseille.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78ed5a3370>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ac-orleans-tours.fr,"HTTPSConnectionPool(host='ac-orleans-tours.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78ef23fac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ac-orleans-tours.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f2afadc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ac-versailles.fr,"HTTPSConnectionPool(host='ac-versailles.fr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f331c490>, 'Connection to ac-versailles.fr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ac-versailles.fr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f4b362e0>, 'Connection to ac-versailles.fr timed out. (connect timeout=2)'))"
academia.cl,"HTTPSConnectionPool(host='academia.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f5b94fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='academia.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78eb9ac820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
academicjournals.org,"HTTPSConnectionPool(host='academicjournals.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='academicjournals.org', port=443): Read timed out. (read timeout=2)"
accesstrade.in.th,"HTTPSConnectionPool(host='accesstrade.in.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='accesstrade.in.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
acerno.sa.it,"HTTPSConnectionPool(host='acerno.sa.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f3f47fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='acerno.sa.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78eb650a00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
acessa.com,"HTTPSConnectionPool(host='acessa.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'acessa.com' doesn't match 'www.acessa.com'"")))","HTTPSConnectionPool(host='acessa.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'acessa.com' doesn't match 'www.acessa.com'"")))"
achs.cl,"HTTPSConnectionPool(host='achs.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f390f220>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='achs.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78ebbb7490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
acm.gov.pt,"HTTPSConnectionPool(host='acm.gov.pt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f3522400>, 'Connection to acm.gov.pt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='acm.gov.pt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f3a7c250>, 'Connection to acm.gov.pt timed out. (connect timeout=2)'))"
acp.pt,"HTTPSConnectionPool(host='www.acp.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.acp.pt', port=443): Read timed out. (read timeout=2)"
adiariocr.com,"HTTPSConnectionPool(host='adiariocr.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='adiariocr.com', port=443): Read timed out. (read timeout=2)"
adidas.cl,"HTTPSConnectionPool(host='www.adidas.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.adidas.cl', port=443): Read timed out. (read timeout=2)"
adidas.com.ar,"HTTPSConnectionPool(host='www.adidas.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.adidas.com.ar', port=443): Read timed out. (read timeout=2)"
adidas.com.br,"HTTPSConnectionPool(host='www.adidas.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.adidas.com.br', port=443): Read timed out. (read timeout=2)"
adidas.gr,"HTTPSConnectionPool(host='www.adidas.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.adidas.gr', port=443): Read timed out. (read timeout=2)"
adidas.sk,"HTTPSConnectionPool(host='www.adidas.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.adidas.sk', port=443): Read timed out. (read timeout=2)"
admtyumen.ru,"HTTPSConnectionPool(host='admtyumen.ru', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='admtyumen.ru', port=443): Read timed out. (read timeout=2)"
aduana.cl,"HTTPSConnectionPool(host='aduana.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f3522490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='aduana.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78eccd2d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
aedb.br,"HTTPSConnectionPool(host='aedb.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f0521910>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='aedb.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f44b3430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
aemps.es,"HTTPSConnectionPool(host='aemps.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78eb3d4490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='aemps.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78eca48610>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
aen.pr.gov.br,"HTTPSConnectionPool(host='aen.pr.gov.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f479a520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='aen.pr.gov.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78ecbcf430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
aeon.jp,"HTTPSConnectionPool(host='aeon.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78ec84c640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='aeon.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f4697640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
affrc.go.jp,"HTTPSConnectionPool(host='affrc.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78ec9c1b80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='affrc.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78ed9ab310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
agenciatributaria.es,"HTTPSConnectionPool(host='agenciatributaria.es', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f78f1199ac0>, 'Connection to agenciatributaria.es timed out. (connect timeout=2)'))","HTTPConnectionPool(host='agenciatributaria.es', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f3dde6d0>, 'Connection to agenciatributaria.es timed out. (connect timeout=2)'))"
agencija-oskar.si,"HTTPSConnectionPool(host='www.agencija-oskar.si', port=443): Read timed out. (read timeout=2)","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
agensir.it,"HTTPSConnectionPool(host='agensir.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))","HTTPSConnectionPool(host='agensir.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))"
agricultura.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='agricultura.gob.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f78f3229fa0>, 'Connection to agricultura.gob.ec timed out. (connect timeout=2)'))"
agro.bg,"HTTPSConnectionPool(host='agro.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='agro.bg', port=443): Read timed out. (read timeout=2)"
agroakademija.lt,"HTTPSConnectionPool(host='agroakademija.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'agroakademija.lt' doesn't match either of '*.lzukt.lt', 'lzukt.lt'"")))","HTTPConnectionPool(host='www.agroakademija.lt', port=80): Read timed out. (read timeout=2)"
agrozona.bg,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ahliionline.com,"HTTPSConnectionPool(host='ahliionline.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78edf45c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ahliionline.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f5a251c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
aianduskool.ee,"HTTPSConnectionPool(host='aianduskool.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.aianduskool.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
aidas.lt,"HTTPSConnectionPool(host='www.aidas.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.aidas.lt', port=443): Read timed out. (read timeout=2)"
airasia.com,"HTTPSConnectionPool(host='www.airasia.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.airasia.com', port=443): Read timed out. (read timeout=2)"
ajapaik.ee,"HTTPSConnectionPool(host='ajapaik.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ajapaik.ee', port=443): Read timed out. (read timeout=2)"
ajio.com,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ajmannews.ae,"HTTPSConnectionPool(host='ajmannews.ae', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ajmannews.ae', port=443): Read timed out. (read timeout=2)"
akcijeikatalozi.rs,"HTTPSConnectionPool(host='akcijeikatalozi.rs', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.akcijeikatalozi.rs', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
akcios-ujsag.hu,"HTTPSConnectionPool(host='akcios-ujsag.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='akcios-ujsag.hu', port=443): Read timed out. (read timeout=2)"
akdeniz.edu.tr,"HTTPSConnectionPool(host='akdeniz.edu.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78f3b44310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='akdeniz.edu.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78f3b550d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
