castorama.fr,"HTTPSConnectionPool(host='www.castorama.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.castorama.fr', port=443): Read timed out. (read timeout=2)"
cba.gov.ar,"HTTPSConnectionPool(host='cba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49574a3a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4956bdf460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cbr.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cbz.si,"HTTPSConnectionPool(host='cbz.si', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cbz.si' doesn't match either of '*.zzzs.si', 'zzzs.si', 'popotnik1.zzzs.si'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cchan.tv,"HTTPSConnectionPool(host='cchan.tv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.cchan.tv', port=443): Read timed out. (read timeout=2)"
ccss.sa.cr,"HTTPSConnectionPool(host='ccss.sa.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4955522e20>, 'Connection to ccss.sa.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ccss.sa.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4956cc7b50>, 'Connection to ccss.sa.cr timed out. (connect timeout=2)'))"
cdd.go.th,"HTTPSConnectionPool(host='cdd.go.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cdd.go.th', port=443): Read timed out. (read timeout=2)"
cdon.dk,"HTTPSConnectionPool(host='cdon.dk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.dk', port=80): Read timed out. (read timeout=2)"
cdon.fi,"HTTPSConnectionPool(host='cdon.fi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.fi', port=80): Read timed out. (read timeout=2)"
cdon.no,"HTTPSConnectionPool(host='cdon.no', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.no', port=80): Read timed out. (read timeout=2)"
cdon.se,"HTTPSConnectionPool(host='cdon.se', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.se', port=80): Read timed out. (read timeout=2)"
cecdebardage.be,"HTTPSConnectionPool(host='cecdebardage.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49588c1910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cecdebardage.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49556f9ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cecile.co.jp,"HTTPSConnectionPool(host='cecile.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cecile.co.jp' doesn't match 'www.cecile.co.jp'"")))","HTTPSConnectionPool(host='www.cecile.co.jp', port=443): Read timed out. (read timeout=2)"
cellphones.com.vn,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
celp.es,"HTTPSConnectionPool(host='celp.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49563a74f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='celp.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4954ca7d30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cerimes.fr,"HTTPSConnectionPool(host='cerimes.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495683fa90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cerimes.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49539a8af0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cerist.dz,"HTTPSConnectionPool(host='cerist.dz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4956886e20>, 'Connection to cerist.dz timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cerist.dz', port=80): Read timed out. (read timeout=2)"
cervantes.es,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='cervantes.es', port=80): Read timed out. (read timeout=2)"
ceskaordinace.cz,"HTTPSConnectionPool(host='www.ceskaordinace.cz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49561a9340>, 'Connection to www.ceskaordinace.cz timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ceskaordinace.cz', port=80): Read timed out. (read timeout=2)"
ceskaposta.cz,"HTTPConnectionPool(host='www.ceskaposta.cz', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ceskaposta.cz', port=80): Read timed out. (read timeout=2)"
ceske-hospudky.cz,"HTTPSConnectionPool(host='ceske-hospudky.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ceske-hospudky.cz' doesn't match 'admin.dokempu.cz'"")))","HTTPConnectionPool(host='www.ceske-hospudky.cz', port=80): Read timed out. (read timeout=2)"
cestakbydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ceylonads.lk,"HTTPSConnectionPool(host='ceylonads.lk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ceylonads.lk', port=443): Read timed out. (read timeout=2)"
cgd.go.th,"HTTPSConnectionPool(host='cgd.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4952d6a5b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cgd.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4952641070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ch10.co.il,"HTTPSConnectionPool(host='ch10.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ch10.co.il', port=443): Read timed out. (read timeout=2)"
chamber.lt,"HTTPSConnectionPool(host='chamber.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chamber.lt', port=443): Read timed out. (read timeout=2)"
chancen.international,"HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)"
checkmate-cbd.it,"HTTPSConnectionPool(host='checkmate-cbd.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='checkmate-cbd.it', port=80): Read timed out. (read timeout=2)"
chiba.lg.jp,"HTTPSConnectionPool(host='chiba.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49584c3f10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='chiba.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4955c47160>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
chillpainai.com,"HTTPSConnectionPool(host='chillpainai.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))","HTTPSConnectionPool(host='chillpainai.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))"
chiquipedia.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
chizumaru.com,"HTTPSConnectionPool(host='chizumaru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495496bfd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='chizumaru.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495496be50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
chooseklaipeda.lt,"HTTPSConnectionPool(host='chooseklaipeda.lt', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='chooseklaipeda.lt', port=80): Read timed out. (read timeout=2)"
chugoku-np.co.jp,"HTTPSConnectionPool(host='chugoku-np.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4952267d60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='chugoku-np.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494fa343d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
chutodnaty.sk,"HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)"
ciberforma.pt,"HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)"
ciela.net,"HTTPSConnectionPool(host='ciela.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='ciela.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
cinematografo.it,"HTTPSConnectionPool(host='cinematografo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))","HTTPSConnectionPool(host='cinematografo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1129)')))"
cipc.co.za,"HTTPSConnectionPool(host='cipc.co.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49558e4910>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cipc.co.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494ebb4070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ciscolinksys.com.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
citc.gov.sa,"HTTPSConnectionPool(host='citc.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citc.gov.sa' doesn't match '*.citc.gov.sa'"")))","HTTPSConnectionPool(host='citc.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citc.gov.sa' doesn't match '*.citc.gov.sa'"")))"
city-adm.lviv.ua,"HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
city-map.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city-map.dk,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city.kawasaki.jp,"HTTPSConnectionPool(host='city.kawasaki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4956742040>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='city.kawasaki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495389a430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
city.nagoya.jp,"HTTPSConnectionPool(host='city.nagoya.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49522b35e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='city.nagoya.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495466c430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
city.saitama.jp,"HTTPSConnectionPool(host='city.saitama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4955dc73a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='city.saitama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49515ab0d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
city.sapporo.jp,"HTTPSConnectionPool(host='city.sapporo.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f494fbce730>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sapporo.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f495675e2e0>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))"
city.sendai.jp,"HTTPSConnectionPool(host='city.sendai.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f494f385640>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sendai.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f494f117ca0>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))"
city24.lv,"HTTPSConnectionPool(host='city24.lv', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4955a8e820>, 'Connection to city24.lv timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='city24.lv', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49559bb100>, 'Connection to city24.lv timed out. (connect timeout=2)'))"
cityexpress.com,"HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)"
citypark.si,"HTTPSConnectionPool(host='www.citypark.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.citypark.si', port=443): Read timed out. (read timeout=2)"
cityportal.gr,"HTTPSConnectionPool(host='cityportal.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cityportal.gr', port=443): Read timed out. (read timeout=2)"
ciu.com.uy,"HTTPSConnectionPool(host='ciu.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4950fcd340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ciu.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495723ea60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ciudaddemendoza.gob.ar,"HTTPSConnectionPool(host='ciudaddemendoza.gob.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciudaddemendoza.gob.ar', port=443): Read timed out. (read timeout=2)"
clasificacionde.org,"HTTPSConnectionPool(host='clasificacionde.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='clasificacionde.org', port=443): Read timed out. (read timeout=2)"
clearnotebooks.com,"HTTPSConnectionPool(host='clearnotebooks.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4957baa4f0>, 'Connection to clearnotebooks.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clearnotebooks.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4956d2a370>, 'Connection to clearnotebooks.com timed out. (connect timeout=2)'))"
clevelandclinicabudhabi.ae,"HTTPSConnectionPool(host='clevelandclinicabudhabi.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'clevelandclinicabudhabi.ae' doesn't match 'www.clevelandclinicabudhabi.ae'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cloudnc.fi,"HTTPSConnectionPool(host='cloudnc.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f494e8a7ac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cloudnc.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4950365dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
club-k.net,"HTTPSConnectionPool(host='club-k.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='club-k.net', port=443): Read timed out. (read timeout=2)"
clubdam.com,"HTTPSConnectionPool(host='clubdam.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495712eb80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='clubdam.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4957ed82b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
clubfactory.com,"HTTPSConnectionPool(host='clubfactory.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f494e8f3b20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='clubfactory.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4955a56a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
clubmb.ee,"HTTPSConnectionPool(host='clubmb.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'clubmb.ee' doesn't match either of 'ns-url-redirect.zoneas.eu', 'www.ns-url-redirect.zoneas.eu'"")))","HTTPSConnectionPool(host='estonia.mercedes-benz-clubs.com', port=443): Read timed out. (read timeout=2)"
clue.co.il,"HTTPSConnectionPool(host='www.clue.co.il', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.clue.co.il', port=80): Read timed out. (read timeout=2)"
cm-lisboa.pt,"HTTPSConnectionPool(host='cm-lisboa.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4954be2730>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPSConnectionPool(host='www.lisboa.pt', port=443): Read timed out. (read timeout=2)"
cm-oeiras.pt,"HTTPSConnectionPool(host='cm-oeiras.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f494e7addc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cm-oeiras.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4956394460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cm-porto.pt,"HTTPSConnectionPool(host='cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
cmru.ac.th,"HTTPSConnectionPool(host='cmru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4956510d90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cmru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4954e8f5b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cmvm.pt,"HTTPSConnectionPool(host='cmvm.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4955a26730>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cmvm.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49539bb9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cnas.ro,"HTTPSConnectionPool(host='cnas.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f494f0ec4c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cnas.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494e92d850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cne.go.cr,"HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
cnr.gob.sv,"HTTPSConnectionPool(host='cnr.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4956b2e790>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cnr.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4954b8c040>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cnrs.fr,"HTTPSConnectionPool(host='cnrs.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4955358520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cnrs.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495270d940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cnss.ma,"HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))","HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))"
cnu.edu.ni,"HTTPSConnectionPool(host='cnu.edu.ni', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))","HTTPConnectionPool(host='cnu.edu.ni', port=80): Read timed out. (read timeout=2)"
co.ee,"HTTPSConnectionPool(host='co.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f494e718700>, 'Connection to co.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='co.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49567d44f0>, 'Connection to co.ee timed out. (connect timeout=2)'))"
cobiss.net,"HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))","HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))"
cocinavital.mx,"HTTPSConnectionPool(host='cocinavital.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cocinavital.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4951e20cd0>, 'Connection to www.cocinavital.mx timed out. (connect timeout=2)'))"
cocokarafine.co.jp,"HTTPSConnectionPool(host='cocokarafine.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495262ad00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cocokarafine.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495286e2e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cocolocala.jp,"HTTPSConnectionPool(host='www.cocolocala.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cocolocala.jp', port=443): Read timed out. (read timeout=2)"
cocolog-nifty.com,"HTTPSConnectionPool(host='cocolog-nifty.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4954eb0580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cocolog-nifty.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f495849c1c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
codedfilm.com.ng,"HTTPSConnectionPool(host='codedfilm.com.ng', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='web.codedfilm.com.ng', port=443): Read timed out. (read timeout=2)"
codedwap.com,"HTTPSConnectionPool(host='codedwap.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='codedwapng.com', port=443): Read timed out. (read timeout=2)"
colciencias.gov.co,"HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
coldiretti.it,"HTTPSConnectionPool(host='coldiretti.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495496b520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='coldiretti.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494eb8a9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
collider.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
colliers.co.nz,"HTTPSConnectionPool(host='colliers.co.nz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='www.colliers.co.nz', port=443): Read timed out. (read timeout=2)"
combank.lk,"HTTPSConnectionPool(host='combank.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495445f220>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='combank.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4955d08a30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
combank.net,"HTTPSConnectionPool(host='combank.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49545a9430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='combank.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4954e8f190>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
commercesuite.com.br,"HTTPSConnectionPool(host='commercesuite.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49505781f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='commercesuite.com.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494e86fa90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
commly.it,"HTTPSConnectionPool(host='commly.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='commly.it', port=80): Read timed out. (read timeout=2)"
companies.lv,"HTTPSConnectionPool(host='companies.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))","HTTPSConnectionPool(host='companies.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))"
company-information.service.gov.uk,"HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))","HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))"
compumir.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='compumir.ru', port=80): Read timed out. (read timeout=2)"
computerworld.bg,"HTTPSConnectionPool(host='computerworld.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='computerworld.bg', port=443): Read timed out. (read timeout=2)"
comune.re.it,"HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
comunidadandina.org,"HTTPSConnectionPool(host='comunidadandina.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4955358430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='comunidadandina.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49564cb9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
conaf.cl,"HTTPSConnectionPool(host='conaf.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f495195ff10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='conaf.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4957ead850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
congreso.gob.pe,"HTTPSConnectionPool(host='congreso.gob.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4957380940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='congreso.gob.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494f0f8e80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
conicyt.cl,"HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)"
conjugacion.es,"HTTPSConnectionPool(host='conjugacion.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4953035970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='conjugacion.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f494eaeaf10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
conmebol.com,"HTTPSConnectionPool(host='conmebol.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'conmebol.com' doesn't match '*.conmebol.com'"")))","HTTPSConnectionPool(host='www.conmebol.com', port=443): Read timed out. (read timeout=2)"
connect.ae,"HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))","HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"
connectselect.be,"HTTPSConnectionPool(host='connectselect.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4957648610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='connectselect.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4952fa6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
