Exception when processing acties.nl
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud97c' in position 1067: surrogates not allowed
################################################################################
Exception when processing alternativeto.net
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udfa2' in position 1492: surrogates not allowed
################################################################################
Exception when processing cylex.at
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udb73' in position 3086: surrogates not allowed
################################################################################
Exception when processing cylex.cl
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udd7f' in position 3052: surrogates not allowed
################################################################################
Exception when processing cylex.dk
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc86' in position 3133: surrogates not allowed
################################################################################
Exception when processing cylex.no
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udbca' in position 3073: surrogates not allowed
################################################################################
Exception when processing filmos.org
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud85d' in position 3428: surrogates not allowed
################################################################################
Exception when processing geekflare.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc6c' in position 3363: surrogates not allowed
################################################################################
Exception when processing investing.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udb02' in position 899: surrogates not allowed
################################################################################
Exception when processing kemik.gt
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udaea' in position 3409: surrogates not allowed
################################################################################
Exception when processing lindaikejisblog.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\ude56' in position 436: surrogates not allowed
################################################################################
Exception when processing opgaver.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udf37' in position 3435: surrogates not allowed
################################################################################
Exception when processing razoesparaacreditar.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udf60' in position 3099: surrogates not allowed
################################################################################
Exception when processing selfridges.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\uda87' in position 3384: surrogates not allowed
################################################################################
Exception when processing sjeverni.info
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud809' in position 3138: surrogates not allowed
################################################################################
Exception when processing vitals.com
################################################################################
Traceback (most recent call last):
  File "./test_encoding.py", line 96, in <module>
    normalizer_result = charset_normalizer.detect(response.content)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/legacy.py", line 20, in detect
    r = CnM.from_bytes(byte_str).best().first()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in from_bytes
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 517, in <listcomp>
    fingerprint_tests = [el.fingerprint == cnm.fingerprint for el in matches]
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 259, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/home/jarek/.pyenv/versions/test_encoding/lib/python3.8/site-packages/charset_normalizer/normalizer.py", line 267, in output
    return str(self).encode(encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\uda58' in position 3373: surrogates not allowed
################################################################################
