moi.gov.sa,"HTTPSConnectionPool(host='moi.gov.sa', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f573b323910>, 'Connection to moi.gov.sa timed out. (connect timeout=2)'))","HTTPConnectionPool(host='moi.gov.sa', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f573b026070>, 'Connection to moi.gov.sa timed out. (connect timeout=2)'))"
moj.go.jp,"HTTPSConnectionPool(host='moj.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573b3236a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='moj.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573ab2a370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
moj.gov.sa,"HTTPSConnectionPool(host='moj.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='moj.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
moja-delatnost.rs,"HTTPSConnectionPool(host='moja-delatnost.rs', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='moja-delatnost.rs', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
mojakompanija.com,"HTTPSConnectionPool(host='www.mojakompanija.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mojakompanija.com', port=443): Read timed out. (read timeout=2)"
momoshop.com.tw,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
mondaq.com,"HTTPSConnectionPool(host='mondaq.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573a2d6370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mondaq.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573965ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mondovolantino.it,"HTTPSConnectionPool(host='mondovolantino.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'mondovolantino.it' doesn't match 'www.mondovolantino.it'"")))","HTTPSConnectionPool(host='mondovolantino.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'mondovolantino.it' doesn't match 'www.mondovolantino.it'"")))"
montaggimobilitorino.it,"HTTPSConnectionPool(host='montaggimobilitorino.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='montaggimobilitorino.it', port=80): Read timed out. (read timeout=2)"
montreal.qc.ca,"HTTPSConnectionPool(host='montreal.qc.ca', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5735a28160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='montreal.qc.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573629f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
moph.go.th,"HTTPSConnectionPool(host='moph.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57355a5340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='moph.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5736943850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mopt.go.cr,"HTTPSConnectionPool(host='mopt.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573a1aa0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='mopt.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573a6b2a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
morelos.gob.mx,"HTTPSConnectionPool(host='morelos.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='morelos.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
mosquitoproject.org,"HTTPSConnectionPool(host='mosquitoproject.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='mosquitoproject.org', port=80): Read timed out. (read timeout=2)"
mots.go.th,"HTTPSConnectionPool(host='mots.go.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mots.go.th', port=443): Read timed out. (read timeout=2)"
movistar.com.ar,"HTTPSConnectionPool(host='movistar.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='movistar.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
movistarplus.es,"HTTPSConnectionPool(host='movistarplus.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'movistarplus.es' doesn't match either of '*.dof6.com', 'dof6.com'"")))","HTTPSConnectionPool(host='www.movistar.es', port=443): Read timed out. (read timeout=2)"
mps.hr,"HTTPSConnectionPool(host='mps.hr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f573198ddf0>, 'Connection to mps.hr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='mps.hr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5735ceba00>, 'Connection to mps.hr timed out. (connect timeout=2)'))"
mpsp.mp.br,"HTTPSConnectionPool(host='mpsp.mp.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57386d3550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mpsp.mp.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5736f8a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mrdiy.com.my,"HTTPSConnectionPool(host='www.mrdiy.com.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mrdiy.com.my', port=443): Read timed out. (read timeout=2)"
mscbs.gob.es,"HTTPSConnectionPool(host='mscbs.gob.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573929eeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mscbs.gob.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573b40bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
msp.gob.ec,"HTTPSConnectionPool(host='msp.gob.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5731c8d340>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='msp.gob.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5735c5b460>: Failed to establish a new connection: [Errno 111] Connection refused'))"
mspas.gob.gt,"HTTPSConnectionPool(host='mspas.gob.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='mspas.gob.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
msudrf.ru,"HTTPSConnectionPool(host='msudrf.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='msudrf.ru', port=80): Read timed out. (read timeout=2)"
mt.gov.vn,"HTTPSConnectionPool(host='mt.gov.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mt.gov.vn', port=443): Read timed out. (read timeout=2)"
mtps.gob.sv,"HTTPSConnectionPool(host='mtps.gob.sv', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f57361ce100>, 'Connection to mtps.gob.sv timed out. (connect timeout=2)'))","HTTPConnectionPool(host='mtps.gob.sv', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5730ad5340>, 'Connection to mtps.gob.sv timed out. (connect timeout=2)'))"
mtroos.com,"HTTPSConnectionPool(host='mtroos.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mtroos.com', port=443): Read timed out. (read timeout=2)"
mtv.it,"HTTPSConnectionPool(host='www.mtv.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mtv.it', port=443): Read timed out. (read timeout=2)"
mufg.jp,"HTTPSConnectionPool(host='mufg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57319d4700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mufg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5734afa790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
multicoisas.com.br,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
museumthailand.com,"HTTPSConnectionPool(host='museumthailand.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f573a6f2fa0>, 'Connection to museumthailand.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='museumthailand.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f57394afd90>, 'Connection to museumthailand.com timed out. (connect timeout=2)'))"
musicity.gr,"HTTPSConnectionPool(host='musicity.gr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5739917e80>, 'Connection to musicity.gr timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.musicity.gr', port=443): Read timed out. (read timeout=2)"
musor.tv,Exceeded 30 redirects.,Exceeded 30 redirects.
muzika.hr,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
muzikbahcesi.com,"HTTPSConnectionPool(host='muzikbahcesi.com', port=443): Read timed out.","HTTPSConnectionPool(host='muzikbahcesi.com', port=443): Read timed out."
mvb.lt,"HTTPSConnectionPool(host='mvb.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573a4087f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mvb.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5736a43f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mvep.hr,"HTTPSConnectionPool(host='mvep.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5738f33fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mvep.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57333f5bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mydict.com,"HTTPSConnectionPool(host='mydict.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mydict.com', port=443): Read timed out. (read timeout=2)"
mydns.jp,"HTTPSConnectionPool(host='mydns.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573611c820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mydns.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5731d86e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mynotebook.am,"HTTPSConnectionPool(host='mynotebook.am', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573b4c9f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mynotebook.am', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5739b73a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mypornsnap.top,"HTTPSConnectionPool(host='mypornsnap.top', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f57384d92b0>, 'Connection to mypornsnap.top timed out. (connect timeout=2)'))","HTTPConnectionPool(host='mypornsnap.top', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f573a047640>, 'Connection to mypornsnap.top timed out. (connect timeout=2)'))"
myq-see.com,"HTTPSConnectionPool(host='myq-see.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57328be580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='myq-see.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573191cc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
myshop.lk,"HTTPSConnectionPool(host='www.myshop.lk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.myshop.lk', port=443): Read timed out. (read timeout=2)"
myshopping.com.au,"HTTPSConnectionPool(host='myshopping.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f573191c250>, 'Connection to myshopping.com.au timed out. (connect timeout=2)'))","HTTPConnectionPool(host='myshopping.com.au', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f57384d9220>, 'Connection to myshopping.com.au timed out. (connect timeout=2)'))"
mysound.jp,"HTTPSConnectionPool(host='mysound.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='mysound.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
n-sport.net,"HTTPSConnectionPool(host='n-sport.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5738e9dca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='n-sport.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5739f46610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
n11.com,"HTTPSConnectionPool(host='n11.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5738528280>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='n11.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573940dd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
na.se,"HTTPSConnectionPool(host='na.se', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.na.se', port=443): Read timed out. (read timeout=2)"
naftemporiki.gr,"HTTPSConnectionPool(host='naftemporiki.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='naftemporiki.gr', port=443): Read timed out. (read timeout=2)"
nagano.lg.jp,"HTTPSConnectionPool(host='nagano.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5733b780d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='nagano.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5734afa7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
nagoya-u.ac.jp,"HTTPSConnectionPool(host='nagoya-u.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57390507c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='nagoya-u.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573abe4d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
nairobiwire.com,"HTTPSConnectionPool(host='nairobiwire.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='nairobiwire.com', port=80): Read timed out. (read timeout=2)"
najnakupi.si,"HTTPSConnectionPool(host='www.najnakupi.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.najnakupi.si', port=443): Read timed out. (read timeout=2)"
nam.fi,"HTTPSConnectionPool(host='nam.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57387082b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='nam.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5730724040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
naoussa.be,"HTTPSConnectionPool(host='naoussa.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573539f580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='naoussa.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5731933d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
nasezdravie.sk,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
nashiterecepti.com,"HTTPSConnectionPool(host='nashiterecepti.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f572f300910>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='nashiterecepti.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f572f251040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
natural-soap-directory.org,"HTTPSConnectionPool(host='natural-soap-directory.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573a323f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='natural-soap-directory.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f573881d370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
naturum.ne.jp,"HTTPSConnectionPool(host='naturum.ne.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='naturum.ne.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
