salud.gob.ec,"HTTPSConnectionPool(host='salud.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salud.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
salud.gob.mx,"HTTPSConnectionPool(host='salud.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbea112b0>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='salud.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbeb62550>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))"
sama.gov.sa,"HTTPSConnectionPool(host='sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samrate.com,"HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samregion.ru,"HTTPSConnectionPool(host='samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanarmed.com,"HTTPSConnectionPool(host='www.sanarmed.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sanarmed.com', port=443): Read timed out. (read timeout=2)"
sangfans.com,"HTTPSConnectionPool(host='sangfans.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sangfans.com', port=443): Read timed out. (read timeout=2)"
sanita.fvg.it,"HTTPSConnectionPool(host='sanita.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc284df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanita.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbe783bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanita.puglia.it,"HTTPSConnectionPool(host='sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanitex.eu,"HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanjoseahora.com.uy,"HTTPSConnectionPool(host='sanjoseahora.com.uy', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sanjoseahora.com.uy', port=443): Read timed out. (read timeout=2)"
santander.cl,"HTTPSConnectionPool(host='santander.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbde17c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santander.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbc165e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sante.gov.ma,"HTTPSConnectionPool(host='sante.gov.ma', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbb551dc0>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sante.gov.ma', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbbd39eb0>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))"
santos.sp.gov.br,"HTTPSConnectionPool(host='santos.sp.gov.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbf3aadc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santos.sp.gov.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbbb8a2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
santotomas.cl,"HTTPSConnectionPool(host='santotomas.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb2ef3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santotomas.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbeded190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanu.ac.rs,"HTTPSConnectionPool(host='sanu.ac.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbd4bbd90>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sanu.ac.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbc8247c0>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))"
sanyonews.jp,"HTTPSConnectionPool(host='sanyonews.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb1256d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanyonews.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbd0416a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sapo.vn,"HTTPSConnectionPool(host='www.sapo.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb008ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPSConnectionPool(host='www.sapo.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbd1e6c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saps.gov.za,"HTTPSConnectionPool(host='saps.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb3e27f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saps.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbb4091f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarahanews.net,"HTTPConnectionPool(host='sarahanews.net', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sarahanews.net', port=80): Read timed out. (read timeout=2)"
sarandi690.com.uy,"HTTPSConnectionPool(host='sarandi690.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb378250>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sarandi690.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbb409df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarawak.gov.my,"HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)"
sat.gob.mx,"HTTPSConnectionPool(host='sat.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='wwwmat.sat.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
satofull.jp,"HTTPSConnectionPool(host='satofull.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecba107580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satofull.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbc917610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
satori.lv,"HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)"
satriwit3.ac.th,"HTTPSConnectionPool(host='satriwit3.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc824b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satriwit3.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbb36c250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saudedireta.com.br,"HTTPSConnectionPool(host='saudedireta.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.saudedireta.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
savba.sk,"HTTPSConnectionPool(host='savba.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecba6d4df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='savba.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecba0b9310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sawahpress.com,"HTTPSConnectionPool(host='sawahpress.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sawahpress.com', port=80): Read timed out. (read timeout=2)"
sayellow.com,"HTTPSConnectionPool(host='sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sbp.com.br,"HTTPSConnectionPool(host='sbp.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecb8b52760>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sbp.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbb405940>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))"
sbp.org.pk,"HTTPSConnectionPool(host='sbp.org.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb8b52f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sbp.org.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbebfdd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sc-celje.si,"HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)"
scba.gov.ar,"HTTPSConnectionPool(host='scba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb8ca8d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb8a7ae80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scghome.com,"HTTPSConnectionPool(host='scghome.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='scghome.com', port=443): Read timed out. (read timeout=2)"
sch.in.ua,"HTTPSConnectionPool(host='sch.in.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc458a30>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='schoolchampion.in.ua', port=80): Read timed out. (read timeout=2)"
schip.io,"HTTPSConnectionPool(host='schip.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc8845b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='schip.io', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb8a20460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.bo,"HTTPSConnectionPool(host='scielo.org.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb4053a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='scielo.org.bo', port=80): Read timed out. (read timeout=2)"
scielo.org.co,"HTTPSConnectionPool(host='scielo.org.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbda1d790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb83b7a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.pe,"HTTPSConnectionPool(host='scielo.org.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb9021430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbd45d2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.za,"HTTPSConnectionPool(host='scielo.org.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb7ba9820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbb3ec220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.sa.cr,"HTTPSConnectionPool(host='scielo.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbba8eac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbd9ee2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scjn.gob.mx,"HTTPSConnectionPool(host='scjn.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb8a16340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scjn.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbdb9e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scoilnet.ie,"HTTPSConnectionPool(host='scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
scotiabankcolpatria.com,"HTTPSConnectionPool(host='scotiabankcolpatria.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbe508250>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scotiabankcolpatria.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb969f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
screenrant.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
scv.si,"HTTPSConnectionPool(host='scv.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb707b580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scv.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbc339ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sdetmi.com,"HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)"
sdp.gov.co,"HTTPSConnectionPool(host='sdp.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecb6e2cc40>, 'Connection to sdp.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sdp.gov.co', port=80): Read timed out. (read timeout=2)"
seattletimes.com,"HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)"
sec.or.th,"HTTPSConnectionPool(host='sec.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc0a74f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sec.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbf3aac40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
secretcv.com,"HTTPSConnectionPool(host='secretcv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.secretcv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
secure-folders.com,"HTTPConnectionPool(host='www.secure-folders.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.secure-folders.com', port=80): Read timed out. (read timeout=2)"
seedly.sg,"HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)"
seguridadpublica.go.cr,"HTTPSConnectionPool(host='seguridadpublica.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb701ce50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='seguridadpublica.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecba1133d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sej.co.jp,"HTTPSConnectionPool(host='sej.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbdc77670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sej.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb7c397c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
selangor.gov.my,"HTTPSConnectionPool(host='selangor.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb7c39880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='selangor.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbcb84fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
semarnat.gob.mx,"HTTPSConnectionPool(host='semarnat.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecb6c83190>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='semarnat.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecb590f760>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))"
semmelweis.hu,"HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)"
sena.edu.co,"HTTPSConnectionPool(host='sena.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbd1c32b0>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sena.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecb6e67be0>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))"
senac.br,"HTTPSConnectionPool(host='senac.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb889f4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senac.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbdbbfd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senado.gob.mx,"HTTPSConnectionPool(host='senado.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc365910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senado.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb574dfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senate.go.th,"HTTPSConnectionPool(host='senate.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb59b8970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senate.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb70cd910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sep.gob.mx,"HTTPSConnectionPool(host='sep.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb8c56e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sep.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb6d42490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sephora.fr,"HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)"
sephora.pl,"HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)"
sephora.sa,"HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)"
sepyc.gob.mx,"HTTPSConnectionPool(host='sepyc.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecb889f340>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sepyc.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecb7eb4bb0>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))"
sernac.cl,"HTTPSConnectionPool(host='sernac.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbb645340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sernac.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbdceff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
servina.net,"HTTPSConnectionPool(host='servina.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='servina.net', port=443): Read timed out. (read timeout=2)"
set.edu.br,"HTTPSConnectionPool(host='set.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecb5394c40>, 'Connection to set.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='set.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecb8c85520>, 'Connection to set.edu.br timed out. (connect timeout=2)'))"
sfax.com.tn,"HTTPSConnectionPool(host='sfax.com.tn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sfax.com.tn' doesn't match either of 'cpanel.sfax.com.tn', 'cpcalendars.sfax.com.tn', 'cpcontacts.sfax.com.tn', 'mail.sfax.com.tn', 'webdisk.sfax.com.tn', 'webmail.sfax.com.tn', 'www.sfax.com.tn'"")))","HTTPConnectionPool(host='sfax.com.tn', port=80): Read timed out. (read timeout=2)"
sfp.org.pl,"HTTPSConnectionPool(host='sfp.org.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sfp.org.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
sgg.gov.ma,"HTTPSConnectionPool(host='sgg.gov.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbc6de820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sgg.gov.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbd24cbb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sggw.pl,"HTTPSConnectionPool(host='sggw.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='sggw.edu.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sgk.gov.tr,"HTTPSConnectionPool(host='sgk.gov.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb7ffa9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.sgk.gov.tr', port=80): Read timed out. (read timeout=2)"
sgmagazine.com,"HTTPSConnectionPool(host='sgmagazine.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='sgmagazine.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
sharp.co.jp,"HTTPSConnectionPool(host='sharp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbd8c73a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sharp.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb80c2cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
shd.gov.co,"HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
shooks.co.il,"HTTPSConnectionPool(host='www.shooks.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shooks.co.il', port=443): Read timed out. (read timeout=2)"
shop.by,"HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)"
shopfacil.com.br,"HTTPSConnectionPool(host='shopfacil.com.br', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='shopfacil.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbbe31ee0>, 'Connection to shopfacil.com.br timed out. (connect timeout=2)'))"
shoptime.com.br,"HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)"
shopu.ro,"HTTPSConnectionPool(host='www.shopu.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shopu.ro', port=443): Read timed out. (read timeout=2)"
showcase-tv.com,"HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))","HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))"
shufersal.co.il,"HTTPSConnectionPool(host='shufersal.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbebfdf10>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shufersal.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbbe13040>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))"
siammakro.co.th,"HTTPSConnectionPool(host='siammakro.co.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbd6470a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='siammakro.co.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb52ed520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
siauliuraj.lt,"HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))","HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))"
sib.gob.gt,"HTTPSConnectionPool(host='sib.gob.gt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb96892e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sib.gob.gt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb51462e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
siboif.gob.ni,"HTTPSConnectionPool(host='siboif.gob.ni', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbc2f53d0>, 'Connection to siboif.gob.ni timed out. (connect timeout=2)'))","HTTPConnectionPool(host='siboif.gob.ni', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecb52a6ac0>, 'Connection to siboif.gob.ni timed out. (connect timeout=2)'))"
sic.gov.co,"HTTPSConnectionPool(host='sic.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sic.gov.co' doesn't match 'www.sic.gov.co'"")))","HTTPConnectionPool(host='sic.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbcb40340>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))"
sicad.gov.tn,"HTTPSConnectionPool(host='sicad.gov.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbd9eec40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sicad.gov.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbcd34040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sieviesuklubs.lv,"HTTPSConnectionPool(host='sieviesuklubs.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.sieviesuklubs.lv', port=80): Read timed out. (read timeout=2)"
sify.com,"HTTPSConnectionPool(host='www.sify.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbbb52ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sify.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecb52b6640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sigmaaldrich.com,"HTTPSConnectionPool(host='sigmaaldrich.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sigmaaldrich.com' doesn't match either of 'www.sigmaaldrich.com', 'www.sigma-aldrich.com'"")))","HTTPSConnectionPool(host='www.sigmaaldrich.com', port=443): Read timed out. (read timeout=2)"
signe-moi.com,"HTTPSConnectionPool(host='signe-moi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb6fcaa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='signe-moi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbdbbfeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
significadosbr.com.br,"HTTPSConnectionPool(host='significadosbr.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.significadosbr.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
sii.cl,"HTTPSConnectionPool(host='sii.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbd7df3a0>, 'Connection to sii.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sii.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fecbcc946d0>, 'Connection to sii.cl timed out. (connect timeout=2)'))"
sik.si,"HTTPSConnectionPool(host='sik.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecbdc5c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sik.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecbc365d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
singaporeair.com,"HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)"
singaporelegaladvice.com,"HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)"
singaporemotherhood.com,"HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)"
sipdf.info,"HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out.","HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out."
sirvintos.lt,"HTTPSConnectionPool(host='sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sis.gov.eg,"HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sistory.si,"HTTPSConnectionPool(host='sistory.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecbd74ff70>, 'Connection to sistory.si timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='sistory.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fecb73d5850>, 'Connection to sistory.si timed out. (connect timeout=2)'))"
sitfit.si,"HTTPSConnectionPool(host='www.sitfit.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sitfit.si', port=443): Read timed out. (read timeout=2)"
sjittv.co,"HTTPConnectionPool(host='www.sjittv.co', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.sjittv.co', port=80): Read timed out. (read timeout=2)"
