salud.gob.ec,"HTTPSConnectionPool(host='salud.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salud.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
salud.gob.mx,"HTTPSConnectionPool(host='salud.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1660322f70>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='salud.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f166032d580>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))"
sama.gov.sa,"HTTPSConnectionPool(host='sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samrate.com,"HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samregion.ru,"HTTPSConnectionPool(host='samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanarmed.com,"HTTPSConnectionPool(host='www.sanarmed.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sanarmed.com', port=443): Read timed out. (read timeout=2)"
sangfans.com,"HTTPSConnectionPool(host='sangfans.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sangfans.com', port=443): Read timed out. (read timeout=2)"
sanita.fvg.it,"HTTPSConnectionPool(host='sanita.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165df3b0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanita.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165e7dee50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanita.puglia.it,"HTTPSConnectionPool(host='sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanitex.eu,"HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
santander.cl,"HTTPSConnectionPool(host='santander.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f654a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santander.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d990610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sante.gov.ma,"HTTPSConnectionPool(host='sante.gov.ma', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f165cdcb6d0>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sante.gov.ma', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165d16fc70>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))"
santos.sp.gov.br,"HTTPSConnectionPool(host='santos.sp.gov.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f05f340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santos.sp.gov.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d563910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
santotomas.cl,"HTTPSConnectionPool(host='santotomas.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f253d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santotomas.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d071af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanu.ac.rs,"HTTPSConnectionPool(host='sanu.ac.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f165ce33fd0>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sanu.ac.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165ce28880>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))"
sanyonews.jp,"HTTPSConnectionPool(host='sanyonews.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165e929880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanyonews.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d9899d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saostar.vn,"HTTPSConnectionPool(host='saostar.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='saostar.vn', port=443): Read timed out. (read timeout=2)"
saps.gov.za,"HTTPSConnectionPool(host='saps.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165e37b160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saps.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165faef6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarandi690.com.uy,"HTTPSConnectionPool(host='sarandi690.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165c408a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sarandi690.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d090700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarawak.gov.my,"HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)"
sarkisozum.gen.tr,"HTTPSConnectionPool(host='www.sarkisozum.gen.tr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sarkisozum.gen.tr', port=443): Read timed out. (read timeout=2)"
sat.gob.mx,"HTTPSConnectionPool(host='sat.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='wwwmat.sat.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
satofull.jp,"HTTPSConnectionPool(host='satofull.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f8945e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satofull.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165c90b910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
satori.lv,"HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)"
satriwit3.ac.th,"HTTPSConnectionPool(host='satriwit3.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f2bae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satriwit3.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165e10ca60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saudedireta.com.br,"HTTPSConnectionPool(host='saudedireta.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.saudedireta.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sauevald.ee,"HTTPSConnectionPool(host='sauevald.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sauevald.ee', port=443): Read timed out. (read timeout=2)"
saulnaymazerolles.com,"HTTPConnectionPool(host='www.saulnaymazerolles.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='saulnaymazerolles.com', port=80): Read timed out. (read timeout=2)"
savba.sk,"HTTPSConnectionPool(host='savba.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f3c3c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='savba.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165b6ebeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sawahpress.com,"HTTPSConnectionPool(host='sawahpress.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sawahpress.com', port=80): Read timed out. (read timeout=2)"
sayellow.com,"HTTPSConnectionPool(host='sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sbc.org.pl,"HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)"
sbp.com.br,"HTTPSConnectionPool(host='sbp.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f165adf6c70>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sbp.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165afb7220>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))"
sbp.org.pk,"HTTPSConnectionPool(host='sbp.org.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165ec91430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sbp.org.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165f1ea250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sc-celje.si,"HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sc-celje.si', port=443): Read timed out. (read timeout=2)"
scba.gov.ar,"HTTPSConnectionPool(host='scba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165a443d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165a443340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scghome.com,"HTTPSConnectionPool(host='scghome.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='scghome.com', port=443): Read timed out. (read timeout=2)"
sch.in.ua,"HTTPSConnectionPool(host='sch.in.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f221df0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='schoolchampion.in.ua', port=80): Read timed out. (read timeout=2)"
schip.io,"HTTPSConnectionPool(host='schip.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165a455220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='schip.io', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165a4556a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.co,"HTTPSConnectionPool(host='scielo.org.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165b9c4490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d3e4460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.mx,"HTTPSConnectionPool(host='scielo.org.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f165ce116d0>, 'Connection to scielo.org.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='scielo.org.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165b6ebeb0>, 'Connection to scielo.org.mx timed out. (connect timeout=2)'))"
scielo.org.pe,"HTTPSConnectionPool(host='scielo.org.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165b9e7130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165a455310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.za,"HTTPSConnectionPool(host='scielo.org.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16596358e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165fc15c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.sa.cr,"HTTPSConnectionPool(host='scielo.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165ef646a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d6b9ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scjn.gob.mx,"HTTPSConnectionPool(host='scjn.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f707430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scjn.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165f636eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scoilnet.ie,"HTTPSConnectionPool(host='scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
scotiabankcolpatria.com,"HTTPSConnectionPool(host='scotiabankcolpatria.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165d379820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scotiabankcolpatria.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165e88e640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scouts388.com,"HTTPConnectionPool(host='www.scouts388.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.scouts388.com', port=80): Read timed out. (read timeout=2)"
screenrant.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
scv.si,"HTTPSConnectionPool(host='scv.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165b9c4520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scv.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165e5328b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sdetmi.com,"HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)"
sdp.gov.co,"HTTPSConnectionPool(host='sdp.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16589318e0>, 'Connection to sdp.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sdp.gov.co', port=80): Read timed out. (read timeout=2)"
seattletimes.com,"HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)"
sec.or.th,"HTTPSConnectionPool(host='sec.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165e0f4850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sec.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1658832850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
secretcv.com,"HTTPSConnectionPool(host='secretcv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.secretcv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
seedly.sg,"HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)"
seguridadpublica.go.cr,"HTTPSConnectionPool(host='seguridadpublica.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1657f566a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='seguridadpublica.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16587a0370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
seguso.com,"HTTPSConnectionPool(host='seguso.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='seguso.com', port=443): Read timed out. (read timeout=2)"
sej.co.jp,"HTTPSConnectionPool(host='sej.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1658c425b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sej.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d2fc910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
selangor.gov.my,"HTTPSConnectionPool(host='selangor.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165d3f93a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='selangor.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1657f6a700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
semanaacademica.org.br,"HTTPSConnectionPool(host='semanaacademica.org.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='semanaacademica.org.br', port=443): Read timed out. (read timeout=2)"
semarnat.gob.mx,"HTTPSConnectionPool(host='semarnat.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f165bef6a30>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='semarnat.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1657493c70>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))"
semmelweis.hu,"HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)"
sena.edu.co,"HTTPSConnectionPool(host='sena.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16574f6f70>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sena.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16574939d0>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))"
senac.br,"HTTPSConnectionPool(host='senac.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165c925a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senac.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165747a2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senado.gob.mx,"HTTPSConnectionPool(host='senado.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165e10cc40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senado.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165f907400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senate.go.th,"HTTPSConnectionPool(host='senate.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165eafcf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senate.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1656db3340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sep.gob.mx,"HTTPSConnectionPool(host='sep.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165dff3a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sep.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16587ac1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sephora.fr,"HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)"
sephora.pl,"HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)"
sephora.sa,"HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)"
sepyc.gob.mx,"HTTPSConnectionPool(host='sepyc.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1658b74cd0>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sepyc.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165f31a1c0>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))"
sernac.cl,"HTTPSConnectionPool(host='sernac.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165d9c0700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sernac.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165f3786d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
set.edu.br,"HTTPSConnectionPool(host='set.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f165f312310>, 'Connection to set.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='set.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165e60d2b0>, 'Connection to set.edu.br timed out. (connect timeout=2)'))"
sevenspeed.it,"HTTPSConnectionPool(host='sevenspeed.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sevenspeed.it', port=80): Read timed out. (read timeout=2)"
sfax.com.tn,"HTTPSConnectionPool(host='sfax.com.tn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sfax.com.tn' doesn't match either of 'cpanel.sfax.com.tn', 'cpcalendars.sfax.com.tn', 'cpcontacts.sfax.com.tn', 'mail.sfax.com.tn', 'webdisk.sfax.com.tn', 'webmail.sfax.com.tn', 'www.sfax.com.tn'"")))","HTTPConnectionPool(host='sfax.com.tn', port=80): Read timed out. (read timeout=2)"
sfp.org.pl,"HTTPSConnectionPool(host='sfp.org.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sfp.org.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
sgg.gov.ma,"HTTPSConnectionPool(host='sgg.gov.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165e6a5af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sgg.gov.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165f6c1b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sggw.pl,"HTTPSConnectionPool(host='sggw.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='sggw.edu.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sgk.gov.tr,"HTTPSConnectionPool(host='sgk.gov.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165caba760>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.sgk.gov.tr', port=80): Read timed out. (read timeout=2)"
sgmagazine.com,"HTTPSConnectionPool(host='sgmagazine.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='sgmagazine.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
sharp.co.jp,"HTTPSConnectionPool(host='sharp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165a33e5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sharp.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1656ba64c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
shd.gov.co,"HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
shooks.co.il,"HTTPSConnectionPool(host='www.shooks.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shooks.co.il', port=443): Read timed out. (read timeout=2)"
shop.by,"HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)"
shoptime.com.br,"HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)"
showcase-tv.com,"HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))","HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))"
shufersal.co.il,"HTTPSConnectionPool(host='shufersal.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1658c2adf0>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shufersal.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165f707130>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))"
siammakro.co.th,"HTTPSConnectionPool(host='siammakro.co.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165fbe52e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='siammakro.co.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165d9f8610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
siauliuraj.lt,"HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))","HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))"
sib.gob.gt,"HTTPSConnectionPool(host='sib.gob.gt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165d386220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sib.gob.gt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1657f8f070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
siboif.gob.ni,"HTTPSConnectionPool(host='siboif.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165a46f760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='siboif.gob.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165da32ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sic.gov.co,"HTTPSConnectionPool(host='sic.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sic.gov.co' doesn't match 'www.sic.gov.co'"")))","HTTPConnectionPool(host='sic.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165e6e8790>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))"
sicad.gov.tn,"HTTPSConnectionPool(host='sicad.gov.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165e20ae20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sicad.gov.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1660c07580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sigmaaldrich.com,"HTTPSConnectionPool(host='sigmaaldrich.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sigmaaldrich.com' doesn't match either of 'www.sigmaaldrich.com', 'www.sigma-aldrich.com'"")))","HTTPSConnectionPool(host='www.sigmaaldrich.com', port=443): Read timed out. (read timeout=2)"
signe-moi.com,"HTTPSConnectionPool(host='signe-moi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165a3c66d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='signe-moi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f165e771280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
significadosbr.com.br,"HTTPSConnectionPool(host='significadosbr.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.significadosbr.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
sii.cl,"HTTPSConnectionPool(host='sii.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16587a0610>, 'Connection to sii.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sii.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f165eb07ca0>, 'Connection to sii.cl timed out. (connect timeout=2)'))"
sik.si,"HTTPSConnectionPool(host='sik.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f165f290f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sik.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1658c87100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
singaporeair.com,"HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)"
singaporelegaladvice.com,"HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)"
singaporemotherhood.com,"HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)"
sipdf.info,"HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out.","HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out."
sirvintos.lt,"HTTPSConnectionPool(host='sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sis.gov.eg,"HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
skafeto.com,"HTTPSConnectionPool(host='skafeto.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='skafeto.com', port=443): Read timed out. (read timeout=2)"
