ulaval.ca,"HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
ulusiada.pt,"HTTPSConnectionPool(host='ulusiada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc1666a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ulusiada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dd1c5ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
um.warszawa.pl,"HTTPSConnectionPool(host='um.warszawa.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='www.um.warszawa.pl', port=80): Read timed out. (read timeout=2)"
um5.ac.ma,"HTTPSConnectionPool(host='um5.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63db909c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='um5.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dddacc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uma.es,"HTTPSConnectionPool(host='uma.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63db7b1b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uma.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dd1934c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umanitoba.ca,"HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
umfcd.ro,"HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)"
umich.mx,"HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uminho.pt,"HTTPSConnectionPool(host='uminho.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63daa65640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uminho.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63db22cdc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umm.ac.id,"HTTPSConnectionPool(host='umm.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.umm.ac.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63db056c40>, 'Connection to www.umm.ac.id timed out. (connect timeout=2)'))"
ums.ac.id,"HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
umsa.bo,"HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unach.edu.ec,"HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unad.edu.co,"HTTPSConnectionPool(host='unad.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da9436a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unad.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63da290f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unan.edu.ni,"HTTPSConnectionPool(host='unan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc449fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d9febd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uncoma.edu.ar,"HTTPSConnectionPool(host='uncoma.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc0d60d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uncoma.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63da018910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
undip.ac.id,"HTTPSConnectionPool(host='undip.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='undip.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uned.es,"HTTPSConnectionPool(host='uned.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d9a85670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uned.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d9c59ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unemi.edu.ec,"HTTPSConnectionPool(host='unemi.edu.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63db778be0>, 'Connection to unemi.edu.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unemi.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dbf946d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unescwa.org,"HTTPSConnectionPool(host='unescwa.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d96405b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unescwa.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d96542e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ung.ac.id,"HTTPSConnectionPool(host='ung.ac.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63d9c4d7f0>, 'Connection to ung.ac.id timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ung.ac.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63db486c40>, 'Connection to ung.ac.id timed out. (connect timeout=2)'))"
uni-lj.si,"HTTPSConnectionPool(host='uni-lj.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63d86f8df0>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uni-lj.si', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63daaea6d0>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))"
uni-muenchen.de,"HTTPSConnectionPool(host='uni-muenchen.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dccaffd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-muenchen.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d90c13d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-regensburg.de,"HTTPSConnectionPool(host='uni-regensburg.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da73f6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-regensburg.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63daaa29d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-sofia.bg,"HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)"
uni-vt.bg,"HTTPSConnectionPool(host='uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unibg.it,"HTTPSConnectionPool(host='unibg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d7ed6d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unibg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d8380670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unicamp.br,"HTTPSConnectionPool(host='unicamp.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dab69d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unicamp.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dc81eeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unican.es,"HTTPSConnectionPool(host='unican.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dbcdf160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unican.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d80c2730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unidivers.fr,"HTTPSConnectionPool(host='unidivers.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d8678a00>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unidivers.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63da5c8790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unifap.br,"HTTPSConnectionPool(host='unifap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d8604100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='unifap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d886cb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
unikom.ac.id,"HTTPSConnectionPool(host='unikom.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unikom.ac.id', port=443): Read timed out. (read timeout=2)"
unimal.ac.id,"HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)"
unimet.edu.ve,"HTTPSConnectionPool(host='unimet.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63daaa20d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimet.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d7a2dd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimib.it,"HTTPSConnectionPool(host='unimib.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63db894700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimib.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dcdad8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimilitar.edu.co,"HTTPSConnectionPool(host='unimilitar.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63dd764a00>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unimilitar.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63d9feb220>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))"
uniminuto.edu,"HTTPSConnectionPool(host='uniminuto.edu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63db970760>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uniminuto.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63d7a38df0>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))"
unin.hr,"HTTPSConnectionPool(host='unin.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unin.hr', port=443): Read timed out. (read timeout=2)"
unina.it,"HTTPSConnectionPool(host='unina.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d6e25940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unina.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d86f8d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unios.hr,"HTTPSConnectionPool(host='unios.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d9648c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unios.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d6f429a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipamplona.edu.co,"HTTPSConnectionPool(host='unipamplona.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d9a7a8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipamplona.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d6e25370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipiloto.edu.co,"HTTPSConnectionPool(host='unipiloto.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d9fa3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipiloto.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dae52610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniqlo.com,"HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)"
unirio.br,"HTTPSConnectionPool(host='unirio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d6f5ad30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d7afb0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unirioja.es,"HTTPSConnectionPool(host='unirioja.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dd0dfe80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirioja.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dbf45130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma2.it,"HTTPSConnectionPool(host='uniroma2.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63db334430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uniroma2.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dd193580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma3.it,"HTTPSConnectionPool(host='uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unisa.ac.za,"HTTPSConnectionPool(host='unisa.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unisa.ac.za', port=443): Max retries exceeded with url: /sites/corporate/default (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
unisant.edu.mx,"HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)"
unisba.ac.id,"HTTPSConnectionPool(host='unisba.ac.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da70b610>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unisba.ac.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d71db070>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unisimon.edu.co,"HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unisul.br,"HTTPSConnectionPool(host='www.unisul.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unisul.br', port=443): Read timed out. (read timeout=2)"
unito.it,"HTTPSConnectionPool(host='unito.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63da70bc70>, 'Connection to unito.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unito.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63d5fb25e0>, 'Connection to unito.it timed out. (connect timeout=2)'))"
unium.cz,"HTTPSConnectionPool(host='unium.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.unium.cz', port=80): Read timed out. (read timeout=2)"
univ-msila.dz,"HTTPSConnectionPool(host='univ-msila.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d5adc670>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='univ-msila.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d5e09f10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
univ-setif2.dz,"HTTPSConnectionPool(host='univ-setif2.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da76d2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univ-setif2.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d5e150a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univ-tlemcen.dz,"HTTPSConnectionPool(host='univ-tlemcen.dz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.univ-tlemcen.dz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
univalle.edu.co,"HTTPSConnectionPool(host='univalle.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d5cb6c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univalle.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d5bf6f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univap.br,"HTTPSConnectionPool(host='univap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dac21a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63ddee8a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
universidadviu.com,"HTTPSConnectionPool(host='www.universidadviu.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.universidadviu.com', port=443): Read timed out. (read timeout=2)"
universiteitleiden.nl,"HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)"
univr.it,"HTTPSConnectionPool(host='univr.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63db93ee50>, 'Connection to univr.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='univr.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63d5e15190>, 'Connection to univr.it timed out. (connect timeout=2)'))"
unizd.hr,"HTTPSConnectionPool(host='unizd.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63db3748b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unizd.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63db28cd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unj.ac.id,"HTTPSConnectionPool(host='unj.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='unj.ac.id', port=80): Read timed out. (read timeout=2)"
unl.edu.ec,"HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unl.pt,"HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unlpam.edu.ar,"HTTPSConnectionPool(host='unlpam.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d4ca2460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unlpam.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d6dccc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unmuhjember.ac.id,"HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unne.edu.ar,"HTTPSConnectionPool(host='unne.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da0183a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unne.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d4aeb070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unodc.org,"HTTPSConnectionPool(host='unodc.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da6f05b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unodc.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d4cf3280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unotices.com,"HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)"
unp.ac.id,"HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unpatti.ac.id,"HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)"
unpret.ro,"HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)"
uns.ac.rs,"HTTPSConnectionPool(host='uns.ac.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc70ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uns.ac.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d6af5550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unse.edu.ar,"HTTPSConnectionPool(host='unse.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc1fe9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unse.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d4c6d1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unsrat.ac.id,"HTTPSConnectionPool(host='unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uob.edu.bh,"HTTPSConnectionPool(host='uob.edu.bh', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc649700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uob.edu.bh', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dc115d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uop.gr,"HTTPSConnectionPool(host='uop.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dd5be4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uop.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dda0f610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
up.ac.za,"HTTPSConnectionPool(host='up.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63da8c0130>, 'Connection to up.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='up.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63dce70070>, 'Connection to up.ac.za timed out. (connect timeout=2)'))"
upatras.gr,"HTTPSConnectionPool(host='upatras.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d86f8f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upatras.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dbdb3af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
upb.ro,"HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)"
upcitemdb.com,"HTTPSConnectionPool(host='upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uph.edu,"HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)"
upv.es,"HTTPSConnectionPool(host='upv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d412a100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d411a7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uq.edu.au,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ura.gov.sg,"HTTPSConnectionPool(host='www.ura.gov.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ura.gov.sg', port=443): Read timed out. (read timeout=2)"
uraccan.edu.ni,"HTTPSConnectionPool(host='uraccan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63ddeb5b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uraccan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dc98f130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
urdu2eng.com,"HTTPSConnectionPool(host='www.urdu2eng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.urdu2eng.com', port=443): Read timed out. (read timeout=2)"
urduinc.com,"HTTPSConnectionPool(host='urduinc.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63d3fb1640>, 'Connection to urduinc.com timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.urduinc.com', port=443): Read timed out. (read timeout=2)"
uruguayconcursa.gub.uy,"HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: // (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
us.es,"HTTPSConnectionPool(host='us.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63e0d3b970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='us.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d88605b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usfx.bo,"HTTPSConnectionPool(host='usfx.bo', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usfx.bo', port=80): Read timed out. (read timeout=2)"
uskudar.edu.tr,"HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
usm.my,"HTTPSConnectionPool(host='usm.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63da60c2e0>, 'Connection to usm.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='usm.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63da677610>, 'Connection to usm.my timed out. (connect timeout=2)'))"
usmba.ac.ma,"HTTPSConnectionPool(host='usmba.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dd81d8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usmba.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dcf127f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usnews.com,"HTTPSConnectionPool(host='usnews.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usnews.com', port=80): Read timed out. (read timeout=2)"
uson.mx,"HTTPSConnectionPool(host='uson.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63dbd24520>, 'Connection to uson.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uson.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63dac4d280>, 'Connection to uson.mx timed out. (connect timeout=2)'))"
usta.edu.co,"HTTPSConnectionPool(host='usta.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d4e3c730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usta.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dae52eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uta.edu.ec,"HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)"
utad.pt,"HTTPSConnectionPool(host='www.utad.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.utad.pt', port=443): Read timed out. (read timeout=2)"
utalca.cl,"HTTPSConnectionPool(host='utalca.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63d5bebee0>, 'Connection to utalca.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utalca.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63dbef6550>, 'Connection to utalca.cl timed out. (connect timeout=2)'))"
utb.cz,"HTTPSConnectionPool(host='utb.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'utb.cz' doesn't match either of 'dokumenty.utb.cz', 'smlouvy.utb.cz'"")))","HTTPSConnectionPool(host='www.utb.cz', port=443): Read timed out. (read timeout=2)"
utcluj.ro,"HTTPSConnectionPool(host='utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
utdanningsforskning.no,"HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)"
utl.pt,"HTTPSConnectionPool(host='utl.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc8f6a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utl.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d7a96ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
utlib.ee,"HTTPSConnectionPool(host='utlib.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63d4ce7d00>, 'Connection to utlib.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utlib.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63d8b48d90>, 'Connection to utlib.ee timed out. (connect timeout=2)'))"
utmachala.edu.ec,"HTTPSConnectionPool(host='utmachala.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dd113520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utmachala.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d6b885b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uv.es,"HTTPSConnectionPool(host='uv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dd785a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63dacf9a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uvzsr.sk,"HTTPSConnectionPool(host='uvzsr.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d9adf070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uvzsr.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63da64a340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vaduguns.lv,"HTTPSConnectionPool(host='vaduguns.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dca30f70>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='vaduguns.lv', port=80): Read timed out. (read timeout=2)"
vaga.lt,"HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)"
valeta.bg,"HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)"
valledelcauca.gov.co,"HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
valoda.lv,"HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
varesenews.it,"HTTPSConnectionPool(host='www.varesenews.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.varesenews.it', port=443): Read timed out. (read timeout=2)"
vatican.va,"HTTPSConnectionPool(host='vatican.va', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63db210a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vatican.va', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d6dccd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdi.lt,"HTTPSConnectionPool(host='vdi.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d7a450a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vdi.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d811fcd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdu.lt,"HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)"
vec.go.th,"HTTPSConnectionPool(host='vec.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63d5adc160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vec.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d4dac6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veleposlanistvo.si,"HTTPSConnectionPool(host='veleposlanistvo.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dab715e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='veleposlanistvo.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d40e79a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verangola.net,"HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)"
vergelijken-chappers.be,"HTTPSConnectionPool(host='vergelijken-chappers.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63da7c11c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vergelijken-chappers.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d9a850a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verif.com,"HTTPSConnectionPool(host='verif.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='verif.com', port=80): Read timed out. (read timeout=2)"
verizon.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
verkkokirjasto.fi,"HTTPSConnectionPool(host='verkkokirjasto.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63dc52a100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='verkkokirjasto.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63db840c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veselebydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
