ulaval.ca,"HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
ulusiada.pt,"HTTPSConnectionPool(host='ulusiada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a1a05af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ulusiada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a33ffbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
um.warszawa.pl,"HTTPSConnectionPool(host='um.warszawa.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='www.um.warszawa.pl', port=80): Read timed out. (read timeout=2)"
um5.ac.ma,"HTTPSConnectionPool(host='um5.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a0f87c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='um5.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a3519b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uma.ac.id,"HTTPSConnectionPool(host='uma.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uma.ac.id', port=443): Read timed out. (read timeout=2)"
uma.es,"HTTPSConnectionPool(host='uma.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a0df5940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uma.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a267b6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umanitoba.ca,"HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))"
umfcd.ro,"HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)"
umich.mx,"HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uminho.pt,"HTTPSConnectionPool(host='uminho.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a005a7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uminho.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a0954b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umk.ac.id,"HTTPSConnectionPool(host='umk.ac.id', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='umk.ac.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a0954940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
umm.ac.id,"HTTPSConnectionPool(host='umm.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.umm.ac.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f90a045ca90>, 'Connection to www.umm.ac.id timed out. (connect timeout=2)'))"
ums.ac.id,"HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
umsa.bo,"HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
una.edu.ni,"HTTPSConnectionPool(host='una.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a093fe20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPSConnectionPool(host='www.una.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909ff59c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unach.edu.ec,"HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unad.edu.co,"HTTPSConnectionPool(host='unad.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909fbcae20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unad.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a0a7f280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unan.edu.ni,"HTTPSConnectionPool(host='unan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a1cdddf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909ffc5a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uncoma.edu.ar,"HTTPSConnectionPool(host='uncoma.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909f3d3430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uncoma.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a3359430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
undip.ac.id,"HTTPSConnectionPool(host='undip.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='undip.ac.id', port=80): Read timed out. (read timeout=2)"
uned.ac.cr,"HTTPSConnectionPool(host='uned.ac.cr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uned.ac.cr', port=443): Read timed out. (read timeout=2)"
uned.es,"HTTPSConnectionPool(host='uned.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a07a1af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uned.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909f255b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unemi.edu.ec,"HTTPSConnectionPool(host='unemi.edu.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f909eb45850>, 'Connection to unemi.edu.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unemi.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909f0c3fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unescwa.org,"HTTPSConnectionPool(host='unescwa.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a0641040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unescwa.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a1158670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-lj.si,"HTTPSConnectionPool(host='uni-lj.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f909e3c8f70>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uni-lj.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909e60aaf0>: Failed to establish a new connection: [Errno 113] No route to host'))"
uni-muenchen.de,"HTTPSConnectionPool(host='uni-muenchen.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a21c8850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-muenchen.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909e551850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-regensburg.de,"HTTPSConnectionPool(host='uni-regensburg.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909dd476d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-regensburg.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a03e1580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-sofia.bg,"HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)"
uni-vt.bg,"HTTPSConnectionPool(host='uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unibg.it,"HTTPSConnectionPool(host='unibg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a14b3550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unibg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909ff50e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unicamp.br,"HTTPSConnectionPool(host='unicamp.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909fec7550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unicamp.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909e4e81c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unican.es,"HTTPSConnectionPool(host='unican.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a2a410a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unican.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909e4e8a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unifap.br,"HTTPSConnectionPool(host='unifap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a2219fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='unifap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909da3abe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
unimal.ac.id,"HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)"
unimet.edu.ve,"HTTPSConnectionPool(host='unimet.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a0dc8370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimet.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909da3a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimib.it,"HTTPSConnectionPool(host='unimib.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a0991850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimib.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a16fbdc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimilitar.edu.co,"HTTPSConnectionPool(host='unimilitar.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f909ccc7a60>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unimilitar.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f909cc5bee0>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))"
uniminuto.edu,"HTTPSConnectionPool(host='uniminuto.edu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90a0b0c280>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uniminuto.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f90a11a3430>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))"
unin.hr,"HTTPSConnectionPool(host='unin.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unin.hr', port=443): Read timed out. (read timeout=2)"
unina.it,"HTTPSConnectionPool(host='unina.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909c44b130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unina.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a28554c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unios.hr,"HTTPSConnectionPool(host='unios.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909c0f1790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unios.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a01bc5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipamplona.edu.co,"HTTPSConnectionPool(host='unipamplona.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909e40dc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipamplona.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c459820>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipiloto.edu.co,"HTTPSConnectionPool(host='unipiloto.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a15507f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipiloto.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c14d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniqlo.com,"HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)"
unirio.br,"HTTPSConnectionPool(host='unirio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909e4dc940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c19e280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unirioja.es,"HTTPSConnectionPool(host='unirioja.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909bdc89d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirioja.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c14d910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma2.it,"HTTPSConnectionPool(host='uniroma2.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a39dfac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uniroma2.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909dd2ed60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma3.it,"HTTPSConnectionPool(host='uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unis.edu.gt,"HTTPSConnectionPool(host='unis.edu.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unis.edu.gt', port=443): Read timed out. (read timeout=2)"
unisa.ac.za,"HTTPSConnectionPool(host='unisa.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unisa.ac.za', port=443): Max retries exceeded with url: /sites/corporate/default (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1124)')))"
unisant.edu.mx,"HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)"
unisba.ac.id,"HTTPSConnectionPool(host='unisba.ac.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909ebe4520>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unisba.ac.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c1c3ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unisimon.edu.co,"HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unisul.br,"HTTPSConnectionPool(host='www.unisul.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unisul.br', port=443): Read timed out. (read timeout=2)"
unito.it,"HTTPSConnectionPool(host='unito.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f909b190a60>, 'Connection to unito.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unito.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f909b55ce50>, 'Connection to unito.it timed out. (connect timeout=2)'))"
unium.cz,"HTTPSConnectionPool(host='unium.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.unium.cz', port=80): Read timed out. (read timeout=2)"
univ-msila.dz,"HTTPSConnectionPool(host='univ-msila.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a1d18eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='univ-msila.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a2787ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
univ-oran1.dz,"HTTPSConnectionPool(host='univ-oran1.dz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.univ-oran1.dz', port=443): Read timed out. (read timeout=2)"
univ-setif2.dz,"HTTPSConnectionPool(host='univ-setif2.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909b5dcca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univ-setif2.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909e1d7f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univ-tlemcen.dz,"HTTPSConnectionPool(host='univ-tlemcen.dz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.univ-tlemcen.dz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
univalle.edu.co,"HTTPSConnectionPool(host='univalle.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a2693160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univalle.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909b30b100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univap.br,"HTTPSConnectionPool(host='univap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a27c3fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a251f550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
universiteitleiden.nl,"HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)"
universityresidences.it,"HTTPSConnectionPool(host='www.universityresidences.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.universityresidences.it', port=80): Read timed out. (read timeout=2)"
univr.it,"HTTPSConnectionPool(host='univr.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90a0da1a60>, 'Connection to univr.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='univr.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f909a396b20>, 'Connection to univr.it timed out. (connect timeout=2)'))"
unizd.hr,"HTTPSConnectionPool(host='unizd.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a00a9130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unizd.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909a014340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unj.ac.id,"HTTPSConnectionPool(host='unj.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='unj.ac.id', port=80): Read timed out. (read timeout=2)"
unja.ac.id,"HTTPSConnectionPool(host='unja.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unja.ac.id', port=443): Read timed out. (read timeout=2)"
unl.edu.ec,"HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unl.pt,"HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unlpam.edu.ar,"HTTPSConnectionPool(host='unlpam.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909a27d280>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unlpam.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909a0b2070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unmuhjember.ac.id,"HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unne.edu.ar,"HTTPSConnectionPool(host='unne.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a341a4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unne.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909b1ea130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unodc.org,"HTTPSConnectionPool(host='unodc.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9099ef05b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unodc.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a2a306a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unotices.com,"HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)"
unp.ac.id,"HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unpar.ac.id,"HTTPSConnectionPool(host='unpar.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unpar.ac.id', port=443): Read timed out."
unpatti.ac.id,"HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
unpret.ro,"HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)"
uns.ac.rs,"HTTPSConnectionPool(host='uns.ac.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a1985370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uns.ac.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a36d15b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unse.edu.ar,"HTTPSConnectionPool(host='unse.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909b51b5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unse.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c0d8af0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unsrat.ac.id,"HTTPSConnectionPool(host='unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
untirta.ac.id,"HTTPSConnectionPool(host='untirta.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='untirta.ac.id', port=443): Read timed out. (read timeout=2)"
uob.edu.bh,"HTTPSConnectionPool(host='uob.edu.bh', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909e3afe80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uob.edu.bh', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909da27c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uop.gr,"HTTPSConnectionPool(host='uop.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909c19ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uop.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a11b7310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
up.ac.za,"HTTPSConnectionPool(host='up.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90a2e2e550>, 'Connection to up.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='up.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f90a102c5b0>, 'Connection to up.ac.za timed out. (connect timeout=2)'))"
upatras.gr,"HTTPSConnectionPool(host='upatras.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a2f41850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upatras.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909a2653d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
upb.ro,"HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)"
upcitemdb.com,"HTTPSConnectionPool(host='upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uph.edu,"HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)"
upr.si,"HTTPSConnectionPool(host='www.upr.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.upr.si', port=443): Read timed out. (read timeout=2)"
upv.es,"HTTPSConnectionPool(host='upv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a2d45c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909c206460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uq.edu.au,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
uraccan.edu.ni,"HTTPSConnectionPool(host='uraccan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a25809d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uraccan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a29bbc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
urdu.co,"HTTPSConnectionPool(host='urdu.co', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='urdu.co', port=443): Read timed out. (read timeout=2)"
urdu2eng.com,"HTTPSConnectionPool(host='www.urdu2eng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.urdu2eng.com', port=443): Read timed out. (read timeout=2)"
urduinc.com,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPSConnectionPool(host='www.urduinc.com', port=443): Read timed out. (read timeout=2)"
urm.lt,"HTTPSConnectionPool(host='urm.lt', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='urm.lt', port=80): Read timed out. (read timeout=2)"
uruguayconcursa.gub.uy,"HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1124)')))","HTTPConnectionPool(host='uruguayconcursa.gub.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a18048e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
us.es,"HTTPSConnectionPool(host='us.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a3619d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='us.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a13cd1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usdwellhouse.com,"HTTPSConnectionPool(host='usdwellhouse.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='usdwellhouse.com', port=443): Read timed out. (read timeout=2)"
usfx.bo,"HTTPSConnectionPool(host='usfx.bo', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usfx.bo', port=80): Read timed out. (read timeout=2)"
uskudar.edu.tr,"HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
usm.my,"HTTPSConnectionPool(host='usm.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90a162f460>, 'Connection to usm.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='usm.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f909a265550>, 'Connection to usm.my timed out. (connect timeout=2)'))"
usmba.ac.ma,"HTTPSConnectionPool(host='usmba.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909b643940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usmba.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a30ce430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usnews.com,"HTTPSConnectionPool(host='usnews.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usnews.com', port=80): Read timed out. (read timeout=2)"
uson.mx,"HTTPSConnectionPool(host='uson.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90a11d7b20>, 'Connection to uson.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uson.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9099d856d0>, 'Connection to uson.mx timed out. (connect timeout=2)'))"
usta.edu.co,"HTTPSConnectionPool(host='usta.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a224a220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usta.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a4a3df10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uta.edu.ec,"HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)"
utalca.cl,"HTTPSConnectionPool(host='utalca.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f90a1152f40>, 'Connection to utalca.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utalca.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f90a2ae4280>, 'Connection to utalca.cl timed out. (connect timeout=2)'))"
utcluj.ro,"HTTPSConnectionPool(host='utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
utdanningsforskning.no,"HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)"
utl.pt,"HTTPSConnectionPool(host='utl.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a29019a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utl.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909dc7b640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
utlib.ee,"HTTPSConnectionPool(host='utlib.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f909983c340>, 'Connection to utlib.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utlib.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f90a11f7b20>, 'Connection to utlib.ee timed out. (connect timeout=2)'))"
utn.edu.ec,"HTTPConnectionPool(host='www.utn.edu.ec', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.utn.edu.ec', port=80): Read timed out. (read timeout=2)"
uv.es,"HTTPSConnectionPool(host='uv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a1616400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909e0bebe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uvzsr.sk,"HTTPSConnectionPool(host='uvzsr.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a1b83460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uvzsr.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9099777970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vaduguns.lv,"HTTPSConnectionPool(host='vaduguns.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a31f1550>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='vaduguns.lv', port=80): Read timed out. (read timeout=2)"
vaga.lt,"HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)"
valeta.bg,"HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)"
valledelcauca.gov.co,"HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
valoda.lv,"HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
vatican.va,"HTTPSConnectionPool(host='vatican.va', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909f3d3460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vatican.va', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909b5d0910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdi.lt,"HTTPSConnectionPool(host='vdi.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909b2ff4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vdi.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9099624910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdu.lt,"HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)"
vec.go.th,"HTTPSConnectionPool(host='vec.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a16d82e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vec.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90997c78b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veidas.lt,"HTTPSConnectionPool(host='veidas.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a0374d00>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.veidas.lt', port=80): Read timed out. (read timeout=2)"
veleposlanistvo.si,"HTTPSConnectionPool(host='veleposlanistvo.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909c5fb190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='veleposlanistvo.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a0ec1b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verangola.net,"HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)"
vergelijken-chappers.be,"HTTPSConnectionPool(host='vergelijken-chappers.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f909999ff70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vergelijken-chappers.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a2fe7790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verizon.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
verkkokirjasto.fi,"HTTPSConnectionPool(host='verkkokirjasto.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a3519160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='verkkokirjasto.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909955cf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veselebydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
